email:
  default_from: "alerts@example.com"
  default_smtp_server: "smtp.example.com"
  default_username: "alerts"
  default_password: "secret"

twilio:
  account_sid: "AC1234567890abcdef1234567890abcdef"
  auth_token: "your_auth_token"
  default_from_number: "+1234567890"

slack:
  default_webhook_url: "https://hooks.slack.com/services/xxx/yyy/zzz"
  default_channel: "#alerts"
  default_username: "Alert Bot"
  default_icon_emoji: ":warning:"

webhook:
  default_timeout: 5  # seconds
  default_retries: 3
  default_retry_delay: 1  # seconds
  default_headers:
    Content-Type: "application/json"
    User-Agent: "AlertingSystem/1.0" 