# Resource Optimization Layer Configuration

# Resource discovery settings
discovery:
  enabled: true
  search_paths:
    - "src/core/resource"
    - "src/core/agents"
    - "src/core/tools"
  exclude_patterns:
    - "*.test.py"
    - "*.spec.py"
    - "__init__.py"
  recursive: true
  max_depth: 5

# Resource types and their settings
types:
  cpu:
    enabled: true
    max_concurrent: 3
    timeout: 30
    retry_attempts: 3
    retry_delay: 1
    max_memory_mb: 512
    max_cpu_percent: 80
    optimization_threshold: 0.8

  memory:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    optimization_threshold: 0.8

  network:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    optimization_threshold: 0.8

  disk:
    enabled: true
    max_concurrent: 1
    timeout: 30
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    optimization_threshold: 0.8

  api:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 3
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    optimization_threshold: 0.8

  database:
    enabled: true
    max_concurrent: 2
    timeout: 30
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 512
    max_cpu_percent: 80
    optimization_threshold: 0.8

  cache:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    optimization_threshold: 0.8

  gpu:
    enabled: true
    max_concurrent: 1
    timeout: 30
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 1024
    max_cpu_percent: 80
    optimization_threshold: 0.8

# Optimization strategies and their settings
strategies:
  scaling:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    scale_up_threshold: 0.8
    scale_down_threshold: 0.2

  caching:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    cache_size_mb: 1000
    cache_ttl_seconds: 3600

  batching:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    batch_size: 100
    batch_timeout_seconds: 5

  parallelization:
    enabled: true
    max_concurrent: 3
    timeout: 30
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 512
    max_cpu_percent: 80
    max_workers: 4
    chunk_size: 1000

  load_balancing:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    balance_threshold: 0.2
    rebalance_interval_seconds: 300

  resource_pooling:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    pool_size: 10
    pool_timeout_seconds: 30

  garbage_collection:
    enabled: true
    max_concurrent: 1
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    gc_threshold: 0.8
    gc_interval_seconds: 300

  rate_limiting:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    rate_limit: 100
    burst_limit: 200

# Resource optimization settings
optimization:
  max_concurrent_optimizations: 5
  default_timeout: 30
  default_retry_attempts: 3
  default_retry_delay: 1
  max_retry_delay: 10
  backoff_factor: 2
  validate_optimizations: true
  update_metrics: true
  cleanup_context: true
  optimization_threshold: 0.8

# Resource management
resources:
  monitoring:
    enabled: true
    interval_seconds: 1
    metrics:
      - "cpu_percent"
      - "memory_percent"
      - "network_usage"
      - "disk_usage"
    thresholds:
      cpu_percent: 80
      memory_percent: 80
      network_percent: 80
      disk_percent: 90
    alerts:
      enabled: true
      notification_channels:
        - "log"
        - "metrics"
      cooldown_seconds: 300

  optimization:
    enabled: true
    strategies:
      - "batch_requests"
      - "cache_results"
      - "reduce_payload"
      - "parallel_processing"
    cache:
      enabled: true
      max_size_mb: 1000
      ttl_seconds: 3600
      cleanup_threshold: 0.8

# Error handling
error_handling:
  enabled: true
  max_errors_per_optimizer: 10
  error_patterns:
    - "validation_error"
    - "optimization_error"
    - "resource_error"
    - "timeout_error"
  recovery_strategies:
    validation_error:
      - "clean_data"
      - "validate_format"
      - "check_constraints"
    optimization_error:
      - "retry"
      - "reduce_complexity"
      - "use_alternative"
    resource_error:
      - "free_resources"
      - "scale_down"
      - "wait"
    timeout_error:
      - "increase_timeout"
      - "optimize_processing"
      - "split_task"

# Monitoring
monitoring:
  enabled: true
  metrics:
    - "resource_state"
    - "optimization_time"
    - "optimization_rate"
    - "error_rate"
    - "resource_usage"
    - "efficiency_level"
  retention_days: 30
  alert_thresholds:
    error_rate: 0.05
    resource_usage: 0.8
    optimization_time: 30
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "logs/resources.log"
    max_size_mb: 100
    backup_count: 5

# Context management
context:
  max_history: 100
  max_optimizations: 50
  max_errors: 20
  retention_days: 7
  update_frequency: "hourly"
  cleanup_threshold: 0.8

# Performance optimization
performance:
  max_concurrent_optimization: 5
  optimization_timeout: 30
  batch_size: 10
  cache_size: 1000
  cache_ttl: 3600
  rate_limiting:
    enabled: true
    max_requests_per_minute: 60
    max_tokens_per_minute: 100000 