apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ade-platform
  region: us-west-2
  version: "1.27"

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  nat:
    gateway: Single

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 5
    volumeSize: 100
    iam:
      withAddonPolicies:
        ebs: true
        efs: true
        fsx: true
        cloudWatch: true
        autoScaler: true

  - name: ng-gpu
    instanceType: g4dn.xlarge
    desiredCapacity: 1
    minSize: 0
    maxSize: 3
    volumeSize: 200
    labels:
      nvidia.com/gpu: "true"
    iam:
      withAddonPolicies:
        ebs: true
        efs: true
        fsx: true
        cloudWatch: true
        autoScaler: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver
  - name: aws-efs-csi-driver
  - name: aws-cloudwatch-agent
  - name: aws-node-termination-handler
  - name: aws-load-balancer-controller
  - name: metrics-server
  - name: cluster-autoscaler 