apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ade-platform-alerts
  namespace: monitoring
spec:
  groups:
  - name: ade-platform
    rules:
    - alert: HighCPUUsage
      expr: avg(rate(container_cpu_usage_seconds_total[5m])) by (pod) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage detected
        description: "Pod {{ $labels.pod }} is using {{ $value | humanizePercentage }} CPU"

    - alert: HighMemoryUsage
      expr: avg(container_memory_usage_bytes) by (pod) / avg(container_spec_memory_limit_bytes) by (pod) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High memory usage detected
        description: "Pod {{ $labels.pod }} is using {{ $value | humanizePercentage }} memory"

    - alert: GPUUtilizationHigh
      expr: avg(nvidia_gpu_utilization) by (pod) > 90
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High GPU utilization detected
        description: "Pod {{ $labels.pod }} is using {{ $value }}% GPU"

    - alert: PodCrashLooping
      expr: kube_pod_container_status_restarts_total > 5
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Pod crash looping detected
        description: "Pod {{ $labels.pod }} has restarted {{ $value }} times"

    - alert: NodeNotReady
      expr: kube_node_status_condition{condition="Ready",status="false"} == 1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Node not ready
        description: "Node {{ $labels.node }} is not ready"

    - alert: PersistentVolumeUsageHigh
      expr: kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High PV usage detected
        description: "PersistentVolume {{ $labels.persistentvolume }} is using {{ $value | humanizePercentage }} space" 