# Agent Autonomy Layer Configuration

# Agent types and their capabilities
agents:
  code_analysis:
    enabled: true
    capabilities:
      - "code_analysis"
      - "pattern_recognition"
      - "error_handling"
      - "learning"
    max_retries: 3
    learning_rate: 0.1
    llm_preferences:
      - "gpt-4"
      - "claude-3-opus"
    max_tokens: 4096
    temperature: 0.2

  pattern_recognition:
    enabled: true
    capabilities:
      - "pattern_recognition"
      - "code_analysis"
      - "learning"
    max_retries: 3
    learning_rate: 0.1
    llm_preferences:
      - "gpt-4"
      - "claude-3-opus"
    max_tokens: 2048
    temperature: 0.3

  tool_selection:
    enabled: true
    capabilities:
      - "tool_selection"
      - "resource_optimization"
      - "error_handling"
    max_retries: 3
    learning_rate: 0.1
    llm_preferences:
      - "gpt-3.5-turbo"
      - "claude-3-sonnet"
    max_tokens: 1024
    temperature: 0.1

  resource_optimization:
    enabled: true
    capabilities:
      - "resource_optimization"
      - "tool_selection"
      - "learning"
    max_retries: 3
    learning_rate: 0.1
    llm_preferences:
      - "gpt-4"
      - "claude-3-opus"
    max_tokens: 2048
    temperature: 0.2

# Learning configuration
learning:
  enabled: true
  metrics:
    - "success_rate"
    - "latency"
    - "error_rate"
    - "resource_efficiency"
  retention_days: 30
  update_frequency: "daily"
  min_samples: 100
  max_samples: 1000
  validation_split: 0.2

# Error handling
error_handling:
  enabled: true
  max_retries: 3
  retry_delay: 1
  backoff_factor: 2
  max_retry_delay: 10
  error_patterns:
    - "rate_limit"
    - "quota_exceeded"
    - "api_error"
    - "validation_error"
  recovery_strategies:
    rate_limit:
      - "wait"
      - "reduce_rate"
      - "switch_provider"
    quota_exceeded:
      - "switch_provider"
      - "reduce_usage"
      - "request_quota_increase"
    api_error:
      - "retry"
      - "validate_request"
      - "check_credentials"
    validation_error:
      - "clean_data"
      - "validate_format"
      - "check_constraints"

# Resource optimization
resource_optimization:
  enabled: true
  metrics:
    - "cpu_usage"
    - "memory_usage"
    - "network_usage"
    - "api_calls"
  thresholds:
    cpu_percent: 80
    memory_percent: 80
    network_percent: 80
    api_calls_per_minute: 60
  optimization_strategies:
    - "batch_requests"
    - "cache_results"
    - "reduce_payload"
    - "parallel_processing"

# Monitoring
monitoring:
  enabled: true
  metrics:
    - "agent_state"
    - "task_completion"
    - "error_rate"
    - "resource_usage"
    - "learning_progress"
  retention_days: 30
  alert_thresholds:
    error_rate: 0.05
    resource_usage: 0.8
    task_completion: 0.95
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "logs/agent.log"
    max_size_mb: 100
    backup_count: 5

# Context management
context:
  max_history: 100
  max_actions: 50
  max_errors: 20
  retention_days: 7
  update_frequency: "hourly"
  cleanup_threshold: 0.8

# Performance optimization
performance:
  max_concurrent_tasks: 5
  task_timeout: 30
  batch_size: 10
  cache_size: 1000
  cache_ttl: 3600
  rate_limiting:
    enabled: true
    max_requests_per_minute: 60
    max_tokens_per_minute: 100000 