apiVersion: v1
kind: Namespace
metadata:
  name: ade-dev

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: user-quota
  namespace: ade-dev
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services.nodeports: "2"
    
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-isolation
  namespace: ade-dev
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: ade-dev
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            name: ade-dev
