# Pattern Recognition Layer Configuration

# Pattern discovery settings
discovery:
  enabled: true
  search_paths:
    - "src/core/patterns"
    - "src/core/agents"
    - "src/core/tools"
  exclude_patterns:
    - "*.test.py"
    - "*.spec.py"
    - "__init__.py"
  recursive: true
  max_depth: 5

# Pattern types and their settings
types:
  design_pattern:
    enabled: true
    max_concurrent: 3
    timeout: 30
    retry_attempts: 3
    retry_delay: 1
    max_memory_mb: 512
    max_cpu_percent: 80
    confidence_threshold: 0.8

  code_pattern:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    confidence_threshold: 0.7

  error_pattern:
    enabled: true
    max_concurrent: 1
    timeout: 10
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 128
    max_cpu_percent: 40
    confidence_threshold: 0.9

  performance_pattern:
    enabled: true
    max_concurrent: 2
    timeout: 15
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    confidence_threshold: 0.8

  security_pattern:
    enabled: true
    max_concurrent: 1
    timeout: 20
    retry_attempts: 3
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60
    confidence_threshold: 0.9

  architecture_pattern:
    enabled: true
    max_concurrent: 2
    timeout: 30
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 512
    max_cpu_percent: 80
    confidence_threshold: 0.8

# Pattern categories and their settings
categories:
  creational:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60

  structural:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60

  behavioral:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60

  architectural:
    enabled: true
    max_concurrent: 2
    timeout: 30
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 512
    max_cpu_percent: 80

  concurrency:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60

  error_handling:
    enabled: true
    max_concurrent: 1
    timeout: 10
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 128
    max_cpu_percent: 40

  performance:
    enabled: true
    max_concurrent: 2
    timeout: 15
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60

  security:
    enabled: true
    max_concurrent: 1
    timeout: 20
    retry_attempts: 3
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60

# Pattern recognition settings
recognition:
  max_concurrent_patterns: 5
  default_timeout: 30
  default_retry_attempts: 3
  default_retry_delay: 1
  max_retry_delay: 10
  backoff_factor: 2
  validate_patterns: true
  update_metrics: true
  cleanup_context: true
  confidence_threshold: 0.8

# Resource management
resources:
  monitoring:
    enabled: true
    interval_seconds: 1
    metrics:
      - "cpu_percent"
      - "memory_percent"
      - "network_usage"
      - "disk_usage"
    thresholds:
      cpu_percent: 80
      memory_percent: 80
      network_percent: 80
      disk_percent: 90
    alerts:
      enabled: true
      notification_channels:
        - "log"
        - "metrics"
      cooldown_seconds: 300

  optimization:
    enabled: true
    strategies:
      - "batch_requests"
      - "cache_results"
      - "reduce_payload"
      - "parallel_processing"
    cache:
      enabled: true
      max_size_mb: 1000
      ttl_seconds: 3600
      cleanup_threshold: 0.8

# Error handling
error_handling:
  enabled: true
  max_errors_per_pattern: 10
  error_patterns:
    - "validation_error"
    - "recognition_error"
    - "resource_error"
    - "timeout_error"
  recovery_strategies:
    validation_error:
      - "clean_data"
      - "validate_format"
      - "check_constraints"
    recognition_error:
      - "retry"
      - "reduce_complexity"
      - "use_alternative"
    resource_error:
      - "free_resources"
      - "scale_down"
      - "wait"
    timeout_error:
      - "increase_timeout"
      - "optimize_processing"
      - "split_task"

# Monitoring
monitoring:
  enabled: true
  metrics:
    - "pattern_state"
    - "recognition_time"
    - "recognition_rate"
    - "error_rate"
    - "resource_usage"
    - "confidence_level"
  retention_days: 30
  alert_thresholds:
    error_rate: 0.05
    resource_usage: 0.8
    recognition_time: 30
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "logs/patterns.log"
    max_size_mb: 100
    backup_count: 5

# Context management
context:
  max_history: 100
  max_matches: 50
  max_errors: 20
  retention_days: 7
  update_frequency: "hourly"
  cleanup_threshold: 0.8

# Performance optimization
performance:
  max_concurrent_recognition: 5
  recognition_timeout: 30
  batch_size: 10
  cache_size: 1000
  cache_ttl: 3600
  rate_limiting:
    enabled: true
    max_requests_per_minute: 60
    max_tokens_per_minute: 100000 