from setuptools import setup, find_packages

setup(
    name="ade-model-training",
    version="0.1.0",
    description="A standalone model training application that can be used independently or integrated with ADE",
    author="ADE Team",
    author_email="team@ade-platform.com",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "torch>=1.8.0",
        "torchvision>=0.9.0",
        "numpy>=1.19.0",
        "pandas>=1.2.0",
        "plotly>=5.3.0",
        "pillow>=8.0.0",
        "scikit-learn>=0.24.0",
        "matplotlib>=3.3.0",
        "tensorboard>=2.4.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.0.0",
            "black>=21.0.0",
            "flake8>=3.9.0",
            "mypy>=0.910",
            "pytest-cov>=2.12.0",
            "pytest-mock>=3.6.0",
            "pytest-asyncio>=0.15.0",
            "pytest-xdist>=2.4.0",
            "pytest-timeout>=1.4.0",
            "pytest-randomly>=3.8.0",
            "pytest-sugar>=0.9.4",
            "pytest-html>=3.1.0",
            "pytest-benchmark>=3.4.0",
            "pytest-env>=0.6.2",
        ],
    },
    entry_points={
        "console_scripts": [
            "ade-model-training=ade_model_training.main:main",
        ],
    },
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
) 