# Tool Discovery System Configuration

# Discovery Settings
discovery:
  enabled: true
  paths:
    - src/core/tools/providers
    - src/core/tools/patterns
    - src/core/tools/optimization
  exclude_patterns:
    - "**/__init__.py"
    - "**/test_*.py"
    - "**/*_test.py"
  scan_interval: 300  # seconds

# Tool Validation
validation:
  required_methods:
    - execute
    - validate
    - cleanup
  safety_levels:
    low:
      max_execution_time: 10.0
      max_memory_increase: 500MB
      allowed_operations: all
    medium:
      max_execution_time: 5.0
      max_memory_increase: 100MB
      allowed_operations:
        - file_read
        - file_write
        - network_request
    high:
      max_execution_time: 2.0
      max_memory_increase: 50MB
      allowed_operations:
        - file_read
        - network_request
      required_safety_checks:
        - input_validation
        - output_sanitization
        - resource_limits

# Performance Monitoring
performance:
  metrics:
    - execution_time
    - memory_usage
    - cpu_usage
    - network_io
    - disk_io
  thresholds:
    execution_time:
      warning: 1.0
      error: 5.0
    memory_usage:
      warning: 100MB
      error: 500MB
    cpu_usage:
      warning: 50%
      error: 80%
    network_io:
      warning: 1MB/s
      error: 10MB/s
    disk_io:
      warning: 100KB/s
      error: 1MB/s

# Resource Management
resources:
  limits:
    max_concurrent_tools: 10
    max_total_memory: 1GB
    max_total_cpu: 80%
  cleanup:
    enabled: true
    interval: 60  # seconds
    threshold: 80%  # memory usage

# Dependency Management
dependencies:
  check_interval: 60  # seconds
  auto_resolve: true
  required_packages:
    - psutil>=5.8.0
    - pyyaml>=5.4.1
    - aiohttp>=3.8.0

# Error Handling
error_handling:
  max_retries: 3
  retry_delay: 1  # seconds
  error_threshold: 5  # errors per minute
  recovery_strategies:
    - restart_tool
    - clear_cache
    - release_resources

# Logging
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: file
      path: logs/tool_discovery.log
      max_size: 10MB
      backup_count: 5
    - type: console
      level: INFO

# Pattern Learning Integration
pattern_learning:
  enabled: true
  update_interval: 300  # seconds
  metrics_to_track:
    - execution_patterns
    - resource_usage_patterns
    - error_patterns
  learning_threshold: 100  # samples

# LLM Integration
llm_integration:
  enabled: true
  model: gpt-4
  max_tokens: 1000
  temperature: 0.7
  tasks:
    - tool_optimization
    - pattern_analysis
    - error_diagnosis 