# Tool Integration Layer Configuration

# Tool discovery settings
discovery:
  enabled: true
  search_paths:
    - "src/core/tools"
    - "src/core/agents"
    - "src/core/llm"
  exclude_patterns:
    - "*.test.py"
    - "*.spec.py"
    - "__init__.py"
  recursive: true
  max_depth: 5

# Tool categories and their settings
categories:
  code_analysis:
    enabled: true
    max_concurrent: 3
    timeout: 30
    retry_attempts: 3
    retry_delay: 1
    max_memory_mb: 512
    max_cpu_percent: 80

  pattern_recognition:
    enabled: true
    max_concurrent: 2
    timeout: 20
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60

  tool_selection:
    enabled: true
    max_concurrent: 1
    timeout: 10
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 128
    max_cpu_percent: 40

  resource_optimization:
    enabled: true
    max_concurrent: 2
    timeout: 15
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 256
    max_cpu_percent: 60

  error_handling:
    enabled: true
    max_concurrent: 1
    timeout: 10
    retry_attempts: 3
    retry_delay: 1
    max_memory_mb: 128
    max_cpu_percent: 40

  learning:
    enabled: true
    max_concurrent: 1
    timeout: 30
    retry_attempts: 2
    retry_delay: 1
    max_memory_mb: 512
    max_cpu_percent: 80

# Tool execution settings
execution:
  max_concurrent_tools: 5
  default_timeout: 30
  default_retry_attempts: 3
  default_retry_delay: 1
  max_retry_delay: 10
  backoff_factor: 2
  validate_parameters: true
  check_dependencies: true
  update_metrics: true
  cleanup_context: true

# Resource management
resources:
  monitoring:
    enabled: true
    interval_seconds: 1
    metrics:
      - "cpu_percent"
      - "memory_percent"
      - "network_usage"
      - "disk_usage"
    thresholds:
      cpu_percent: 80
      memory_percent: 80
      network_percent: 80
      disk_percent: 90
    alerts:
      enabled: true
      notification_channels:
        - "log"
        - "metrics"
      cooldown_seconds: 300

  optimization:
    enabled: true
    strategies:
      - "batch_requests"
      - "cache_results"
      - "reduce_payload"
      - "parallel_processing"
    cache:
      enabled: true
      max_size_mb: 1000
      ttl_seconds: 3600
      cleanup_threshold: 0.8

# Error handling
error_handling:
  enabled: true
  max_errors_per_tool: 10
  error_patterns:
    - "rate_limit"
    - "quota_exceeded"
    - "api_error"
    - "validation_error"
    - "dependency_error"
    - "resource_error"
  recovery_strategies:
    rate_limit:
      - "wait"
      - "reduce_rate"
      - "switch_provider"
    quota_exceeded:
      - "switch_provider"
      - "reduce_usage"
      - "request_quota_increase"
    api_error:
      - "retry"
      - "validate_request"
      - "check_credentials"
    validation_error:
      - "clean_data"
      - "validate_format"
      - "check_constraints"
    dependency_error:
      - "check_installation"
      - "install_dependency"
      - "use_alternative"
    resource_error:
      - "free_resources"
      - "scale_down"
      - "wait"

# Monitoring
monitoring:
  enabled: true
  metrics:
    - "tool_state"
    - "execution_time"
    - "success_rate"
    - "error_rate"
    - "resource_usage"
    - "dependency_status"
  retention_days: 30
  alert_thresholds:
    error_rate: 0.05
    resource_usage: 0.8
    execution_time: 30
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "logs/tools.log"
    max_size_mb: 100
    backup_count: 5

# Context management
context:
  max_history: 100
  max_executions: 50
  max_errors: 20
  retention_days: 7
  update_frequency: "hourly"
  cleanup_threshold: 0.8

# Performance optimization
performance:
  max_concurrent_executions: 5
  execution_timeout: 30
  batch_size: 10
  cache_size: 1000
  cache_ttl: 3600
  rate_limiting:
    enabled: true
    max_requests_per_minute: 60
    max_tokens_per_minute: 100000 