version: '3.8'

services:
  test-api:
    build:
      context: ../..
      dockerfile: environments/testing/Dockerfile
    volumes:
      - ../../src:/app/src
      - ../../tests:/app/tests
      - ../../coverage:/app/coverage
    environment:
      - ENVIRONMENT=testing
      - LOG_LEVEL=DEBUG
      - MONGODB_URI=mongodb://admin:testpassword@test-mongodb:27017
      - REDIS_PASSWORD=testredispassword
      - JWT_SECRET=test-secret-key
    depends_on:
      - test-mongodb
      - test-redis
    networks:
      - test-network

  test-mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=testpassword
    networks:
      - test-network

  test-redis:
    image: redis:latest
    command: redis-server --requirepass testredispassword
    networks:
      - test-network

  integration-tests:
    build:
      context: ../..
      dockerfile: environments/testing/Dockerfile
    volumes:
      - ../../src:/app/src
      - ../../tests:/app/tests
      - ../../coverage:/app/coverage
    environment:
      - ENVIRONMENT=testing
      - LOG_LEVEL=DEBUG
      - MONGODB_URI=mongodb://admin:testpassword@test-mongodb:27017
      - REDIS_PASSWORD=testredispassword
      - JWT_SECRET=test-secret-key
    depends_on:
      - test-api
      - test-mongodb
      - test-redis
    networks:
      - test-network
    command: ["pytest", "-v", "--cov=src", "--cov-report=xml", "--cov-report=term-missing", "tests/integration/"]

  performance-tests:
    build:
      context: ../..
      dockerfile: environments/testing/Dockerfile
    volumes:
      - ../../src:/app/src
      - ../../tests:/app/tests
      - ../../performance_results:/app/performance_results
    environment:
      - ENVIRONMENT=testing
      - TARGET_URL=http://test-api:8000
    depends_on:
      - test-api
    networks:
      - test-network
    command: ["python", "-m", "locust", "-f", "tests/performance/locustfile.py", "--headless", "-u", "10", "-r", "1", "--run-time", "1m"]

networks:
  test-network:
    driver: bridge 