# Training Configuration

# General settings
num_episodes: 1000
batch_size: 32
learning_rate: 0.001
checkpoint_frequency: 100
parallel_training: true
max_workers: 4
evaluation_frequency: 100
early_stopping_patience: 10
early_stopping_threshold: 0.001

# Output directory
output_dir: "data/learning/training"

# Algorithm configurations
algorithms:
  dqn:
    enabled: true
    params:
      epsilon: 0.1
      memory_size: 10000
      batch_size: 32
      target_update_freq: 100
      learning_rate: 0.001
      gamma: 0.99
      
  ppo:
    enabled: true
    params:
      learning_rate: 0.0003
      gamma: 0.99
      gae_lambda: 0.95
      clip_epsilon: 0.2
      c1: 1.0  # Value function coefficient
      c2: 0.01  # Entropy coefficient
      n_steps: 2048
      n_epochs: 10
      batch_size: 64
      
  a3c:
    enabled: true
    params:
      learning_rate: 0.0001
      gamma: 0.99
      n_steps: 5
      gae_lambda: 0.95
      entropy_coef: 0.01
      value_loss_coef: 0.5
      max_grad_norm: 0.5
      num_processes: 4 